/*
 * SmoothDialog.java
 *
 * Copyright (c) 2010-2010 CPGeo, LTDA. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of 
 * Centro Potiguar de Geociências LTDA - CPGeo. You shall not disclose
 * such Confidential Information and shall use it only in accordance
 * with the terms of the license agreement you entered into with CPGeo.
 *
 * CPGeo MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. CPGEO SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 * Created: 2 September 2010
 * Last modified: 9 September 2010
 * 
 */
package botoseis.ivelan.temp;

import static java.awt.EventQueue.invokeLater;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import static java.lang.Short.MAX_VALUE;
import static java.lang.System.exit;
import static javax.swing.GroupLayout.Alignment.BASELINE;
import static javax.swing.GroupLayout.Alignment.LEADING;
import static javax.swing.GroupLayout.Alignment.TRAILING;
import static javax.swing.GroupLayout.DEFAULT_SIZE;
import static javax.swing.GroupLayout.PREFERRED_SIZE;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.LayoutStyle.ComponentPlacement.RELATED;

/**
 *
 * @author Williams Lima
 */
public class SmoothDialog extends javax.swing.JDialog {

    boolean answer;

    /* Creates new form SmoothDialog */
    public SmoothDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
    }

    public int getCdpWindow() {
        int ret;
        try {
            ret = parseInt(cdpWindow.getText());
        } catch (Exception e) {
            ret = 0;
        }

        return ret;
    }

    public float getTimeWindow() {
        float ret;
        try {
            ret = parseFloat(timeWindow.getText());
        } catch (Exception e) {
            ret = 0;
        }

        return ret;
    }

    public int getCdpsInterval() {
        int ret;
        try {
            ret = parseInt(dcdp.getText());
        } catch (Exception e) {
            ret = 0;
        }

        return ret;
    }

    public float getTimeInterval() {
        float ret;
        try {
            ret = parseFloat(dtime.getText());
        } catch (Exception e) {
            ret = 0;
        }

        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cdpWindow = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        timeWindow = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dcdp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dtime = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Smoothing parameters");

        jLabel1.setText("CDP window:");

        jLabel2.setText("Time window:");

        btnOK.setText("OK");
        btnOK.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnOKActionPerformed(evt);
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCancelActionPerformed(evt);
        });

        jLabel3.setText("CDPs interval:");

        jLabel4.setText("Time interval:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(TRAILING).addGroup(layout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(RELATED).addComponent(cdpWindow, PREFERRED_SIZE, 48, PREFERRED_SIZE)).addGroup(layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(RELATED).addComponent(dcdp, PREFERRED_SIZE, 48, PREFERRED_SIZE))).addPreferredGap(RELATED).addGroup(layout.createParallelGroup(TRAILING).addGroup(layout.createSequentialGroup().addComponent(jLabel4).addGap(12, 12, 12).addComponent(dtime, PREFERRED_SIZE, 48, PREFERRED_SIZE)).addGroup(layout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(RELATED).addComponent(timeWindow, PREFERRED_SIZE, 48, PREFERRED_SIZE)))).addComponent(jSeparator1, DEFAULT_SIZE, 424, MAX_VALUE)).addContainerGap()).addGroup(TRAILING, layout.createSequentialGroup().addComponent(btnOK, PREFERRED_SIZE, 97, PREFERRED_SIZE).addPreferredGap(RELATED).addComponent(btnCancel, PREFERRED_SIZE, 97, PREFERRED_SIZE).addGap(119, 119, 119)))));
        layout.setVerticalGroup(layout.createParallelGroup(LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(BASELINE).addComponent(jLabel3).addComponent(dcdp, PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE).addComponent(jLabel4).addComponent(dtime, PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE)).addPreferredGap(RELATED).addGroup(layout.createParallelGroup(BASELINE).addComponent(cdpWindow, PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE).addComponent(jLabel1).addComponent(timeWindow, PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE).addComponent(jLabel2)).addPreferredGap(RELATED).addComponent(jSeparator1, PREFERRED_SIZE, 10, PREFERRED_SIZE).addPreferredGap(RELATED).addGroup(layout.createParallelGroup(BASELINE).addComponent(btnOK).addComponent(btnCancel)).addContainerGap(DEFAULT_SIZE, MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (verify()) {
            answer = true;
            setVisible(false);
        } else {
            showMessageDialog(null, "invalid values!");
        }

    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cdpWindow.setText("");
        timeWindow.setText("");
        answer = false;
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    @Override
    public boolean isValid() {
        return answer;
    }

    public boolean verify() {
        return !(timeWindow.getText().trim().isEmpty() || cdpWindow.getText().trim().isEmpty()
                || dcdp.getText().trim().isEmpty() || dtime.getText().trim().isEmpty());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        invokeLater(() -> {
            SmoothDialog dialog = new SmoothDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField cdpWindow;
    private javax.swing.JTextField timeWindow;
    private javax.swing.JTextField dcdp;
    private javax.swing.JTextField dtime;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration
}
